name: Build and Deploy to Google Cloud Run

on:
  push:
    branches:
      - main  

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Extract metadata (e.g. git commit SHA)
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: nurhatmurathan/boilerplate
        tags: type=sha,prefix=commit,format=long

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: nurhatmurathan/boilerplate:${{ github.sha }}

    - name: Setup GCloud CLI
      uses: google-github-actions/setup-gcloud@v0
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: muratkan-trial-v2

    - name: Configure Docker for GCloud CLI
      run: gcloud auth configure-docker

    - name: Deploy to Google Cloud Run
      run: |
        gcloud run deploy django-boilerplate \
          --image=docker.io/nurhatmurathan/boilerplate:${{ github.sha }} \
          --region=us-central1 \
          --allow-unauthenticated \
          --breakglass=JUSTIFICATION \
          --port=8000 \
          --min-instances=1 \
          --max-instances=2
